# -*- coding: utf-8 -*-
"""EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10OxBhVX-TtIMVYWCfo79tOACsB4GwOwH
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
uploaded = files.upload()

# Option 1
df = pd.read_csv("stores_sales_forecasting.csv", encoding='latin1')

# Option 2
df = pd.read_csv("stores_sales_forecasting.csv", encoding='cp1252')

print(df.head())
print(df.info())

df = df[['Order Date', 'Product Name', 'Sales']]
df.columns = ['date', 'product_name', 'sales']

df['date'] = pd.to_datetime(df['date'])
df = df.groupby(['date', 'product_name'])['sales'].sum().reset_index()

